<a href="https://colab.research.google.com/github/Asiya0528/siwes-2026/blob/main/day07_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [5]:
# Replace 'your_file_path.csv' with the actual path to your CSV file
hh = pd.read_csv('/content/sample_data/california_housing_train.csv')

# Display the first 5 rows of the DataFrame to verify
display(hh.head())

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [ ]:
hh['zone']
hh[['hhid','zone', 'sector']]

In [ ]:
urban = hh[hh['sector'] =='Urban']
print(len(urban), "urban households")

In [ ]:
urban_electric = hh[(hh['sector'] == 'Urban) ']
print(len(urban_electric))

In [ ]:
north =hh[(hh['zone'] == 'North West') | (hh['zone'] == 'North East')]

In [ ]:
north = hh[hh['zone'].isin(['North West', 'North East', 'North Central'])]
print(len(north))

In [6]:
hh.sort_values('median_house_value', ascending=False).head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2698,-117.68,33.57,2.0,10008.0,1453.0,3550.0,1139.0,10.1122,500001.0
7156,-118.32,33.77,37.0,627.0,95.0,259.0,106.0,6.8870,500001.0
7157,-118.32,33.75,37.0,1080.0,135.0,366.0,142.0,11.6677,500001.0
7158,-118.32,33.75,33.0,2996.0,398.0,1048.0,387.0,9.2670,500001.0
7159,-118.32,33.74,24.0,6097.0,794.0,2248.0,806.0,10.1357,500001.0
2671,-117.67,33.44,25.0,2994.0,519.0,903.0,410.0,6.6852,500001.0
2668,-117.67,33.47,22.0,2728.0,616.0,1081.0,566.0,1.6393,500001.0
13474,-121.95,37.21,20.0,2345.0,322.0,890.0,276.0,10.0187,500001.0
7057,-118.32,34.13,34.0,1856.0,273.0,540.0,264.0,4.0833,500001.0
13530,-121.96,37.22,35.0,4709.0,723.0,1866.0,694.0,8.4920,500001.0

In [7]:
(hh[hh['longitude'] < -120]
    [['longitude', 'latitude', 'population', 'housing_median_age']]
    .sort_values('population', ascending=False)
    .head(10))

       longitude  latitude  population  housing_median_age
12772    -121.79     36.64     28566.0                11.0
10692    -120.59     34.70     12427.0                29.0
13299    -121.92     37.53     12203.0                 7.0
12586    -121.68     36.72     12153.0                12.0
12475    -121.61     36.69     11272.0                19.0
12018    -121.40     38.47     10329.0                 4.0
13388    -121.94     38.27      9879.0                35.0
13022    -121.86     37.37      8793.0                15.0
11875    -121.35     38.54      8656.0                12.0
11864    -121.35     38.72      8652.0                 2.0